Repository AppScale/appscale, pull requests merged in 2018-02, with the labels that each got.

#2664 Replace reference to deprecated role
  scripts/fast-start.sh
Labels: Priority: High, Status: Approved for merge

#2670 Catch correct BadStatusLine exception
  AppTaskQueue/appscale/taskqueue/push_worker.py
Labels: Priority: High, Status: Approved for merge

#2652 Handle key inequality filter within property value
  AppDB/appscale/datastore/datastore_distributed.py
  AppDB/appscale/datastore/utils.py
Labels: Status: Approved for merge

#2662 Remove unnecessary JSON serialization
  AppController/test/tc_djinn.rb
Labels: Priority: High, Status: Demo requested

#2659 Upgrade pip in virtualenv
  debian/appscale_install_functions.sh
Labels: Priority: High, Status: Demo requested

#2660 Execute tar command with environment variable
  AppController/lib/app_dashboard.rb
Labels: Priority: High, Status: Approved for merge

#2661 Install php-bcmath
  debian/control.xenial
Labels: Priority: High, Status: Approved for merge

#2667 Remove tcp_tw_recycle option
  debian/appscale_install_functions.sh
Labels: Priority: High, Status: Approved for merge

#2663 Updated overview section text.
  README.md
Labels: Status: Review requested

#2671 Don't clear cron jobs during an up
  AppController/djinn.rb
Labels: Priority: High, Status: Review requested

#2658 Haproxy consolidate apps
  AppController/djinn.rb
  AppController/lib/haproxy.rb
  Hermes/appscale/hermes/stats/constants.py
Labels: Status: Approved for merge

#2665 Taskqueue service stats
  AppTaskQueue/appscale/taskqueue/appscale_taskqueue.py
  AppTaskQueue/appscale/taskqueue/constants.py
  AppTaskQueue/appscale/taskqueue/rest_api.py
  AppTaskQueue/appscale/taskqueue/statistics.py
  AppTaskQueue/test/unit/test_service_stats.py
  common/appscale/common/service_stats/categorizers.py
  common/appscale/common/service_stats/stats_manager.py
Labels: Priority: High, Status: Demo requested

#2675 Fix posixpsutil build
  debian/control.jessie
  debian/control.trusty
  debian/control.wheezy
Labels: Status: Review requested

#2668 RM-565 - Script to automate version bump.
  Makefile
  util/bump_version.sh
  util/gen_release_notes.sh
Labels: Status: Demo requested

#2636 Capture Net::ReadTimeout when using Net::HTTP
  AppController/lib/app_manager_client.rb
  AppController/lib/hermes_client.rb
Labels: Status: Approved for merge

#2676 Stick to the duty cycle length
  AppController/djinn.rb
Labels: Status: Demo requested

#2678 Prevent ProjectGroomer worker from stopping
  AppDB/appscale/datastore/scripts/transaction_groomer.py
Labels: Priority: High, Status: Build pending

#2679 Fix calls to master from others ACs.
  AppController/djinn.rb
  AppController/lib/app_controller_client.rb
Labels: Priority: High, Status: Demo requested

#2683 Use prefix for the haproxy app config file
  AppController/lib/haproxy.rb
Labels: Priority: Urgent, Status: Approved for merge

#2681 Run apps without application element in app.yaml
  AppManager/app_manager_server.py
  AppServer/google/appengine/api/appinfo.py
  AppServer/google/appengine/tools/devappserver2/application_configuration.py
  AppServer/google/appengine/tools/devappserver2/application_configuration_test.py
  AppServer/google/appengine/tools/devappserver2/devappserver2.py
Labels: Priority: High, Status: Approved for merge

#2638 Whitelist inbound service warmup
  AdminServer/appscale/admin/constants.py
Labels: Status: Demo requested
