Repository AppScale/appscale, pull requests merged in 2018-12, with the labels that each got.

#2932 Check for valid local source archive
  AdminServer/appscale/admin/instance_manager/source_manager.py
Labels: Priority: High, Status: Approved for merge

#2705 Use zookeeper for stopped versions
  AdminServer/appscale/admin/__init__.py
  AdminServer/appscale/admin/instance_manager/instance_manager.py
  AdminServer/appscale/admin/instance_manager/utils.py
  AppController/djinn.rb
  AppController/djinnServer.rb
  AppController/lib/app_controller_client.rb
  AppController/lib/cron_helper.rb
  AppController/lib/haproxy.rb
  AppController/lib/helperfunctions.rb
  AppController/lib/monit_interface.rb
  AppController/lib/nginx.rb
  AppController/test/tc_djinn.rb
  AppControllerClient/appscale/appcontroller_client/__init__.py
  AppDashboard/test/functional/test_dashboard.py
Labels: Priority: High, Status: Demo requested

#2919 Make communication with rabbitmq async (in Hermes)
  Hermes/appscale/hermes/producers/rabbitmq_stats.py
Labels: Status: Approved for merge

#2833 Add basic pull queue viewer to dashboard
  AppController/djinn.rb
  AppController/lib/app_dashboard.rb
  AppDashboard/dashboard.py
  AppDashboard/lib/app_dashboard_data.py
  AppDashboard/lib/pull_queue_viewer.py
  AppDashboard/static/css/Styles.css
  AppDashboard/templates/taskqueue/project_selector.html
  AppDashboard/templates/taskqueue/queue_selector.html
  AppDashboard/templates/taskqueue/task_selector.html
  AppTaskQueue/appscale/taskqueue/appscale_taskqueue.py
  AppTaskQueue/appscale/taskqueue/rest_api.py
Labels: Priority: High, Status: Demo requested
