Repository AppScale/appscale, pull requests merged in 2018-03, with the labels that each got.

#2672 Allow different instance type per role
  AppController/djinn.rb
  AppController/lib/djinn_job_data.rb
  AppController/lib/infrastructure_manager_client.rb
  AppController/test/tc_djinn.rb
  AppController/test/tc_infrastructure_manager_client.rb
Labels: Priority: High, Status: Demo requested

#2686 RM-587 - 3.5.0 Version bump
  VERSION
Labels: Priority: High, Status: Review requested

#2684 Allow group locks to persist when commits fail
  AppDB/appscale/datastore/cassandra_env/cassandra_interface.py
  AppDB/appscale/datastore/cassandra_env/constants.py
  AppDB/appscale/datastore/cassandra_env/schema.py
  AppDB/appscale/datastore/datastore_distributed.py
  AppDB/appscale/datastore/dbconstants.py
  AppDB/appscale/datastore/groomer.py
  AppDB/appscale/datastore/scripts/datastore.py
  AppDB/appscale/datastore/scripts/prime_cassandra.py
  AppDB/appscale/datastore/scripts/transaction_groomer.py
  AppDB/appscale/datastore/zkappscale/entity_lock.py
  AppDB/appscale/datastore/zkappscale/transaction_manager.py
  AppDB/test/unit/test_datastore_server.py
  scripts/datastore_upgrade.py
Labels: Priority: High, Status: Demo requested

#2685 Don't allow editing entities with datastore viewer
  AppDashboard/lib/datastore_viewer.py
  AppDashboard/templates/datastore/edit.html
  AppDashboard/templates/datastore/viewer.html
  AppServer/google/appengine/tools/devappserver2/admin/datastore_viewer.py
Labels: Priority: High, Status: Demo requested

#2687 RM-589 handle failure on fetching local stats
  Hermes/appscale/hermes/stats/producers/cluster_stats.py
  Hermes/appscale/hermes/stats/producers/tests/test_cluster_stats.py
Labels: Priority: Urgent, Status: Demo requested

#2673 Wait for all load balancers to route instances
  AdminServer/appscale/admin/__init__.py
  AdminServer/appscale/admin/constants.py
Labels: Status: Demo requested

#2693 Remove dead code
  AppController/djinn.rb
  AppController/djinnServer.rb
  AppController/lib/app_controller_client.rb
  AppController/lib/zkinterface.rb
  AppController/test/tc_djinn.rb
  AppController/test_client.rb
Labels: Status: Review requested

#2691 Handle docker as a provider
  scripts/fast-start.sh
Labels: Status: Demo requested

#2692 Use datastore server registry to toggle read-only mode
  AppController/djinn.rb
  AppController/lib/datastore_server.rb
  AppController/lib/zkinterface.rb
Labels: Priority: High, Status: Demo requested

#2590 Add a scatter property to some entities
  AppDB/appscale/datastore/cassandra_env/cassandra_interface.py
  AppDB/appscale/datastore/cassandra_env/schema.py
  AppDB/appscale/datastore/datastore_distributed.py
  AppDB/appscale/datastore/dbconstants.py
  AppDB/appscale/datastore/groomer.py
  AppDB/appscale/datastore/scripts/datastore.py
  AppDB/appscale/datastore/utils.py
Labels: Status: Review requested

#2695 Replace usages of execute_concurrent
  AppDB/appscale/datastore/cassandra_env/cassandra_interface.py
  AppTaskQueue/appscale/taskqueue/queue.py
Labels: Status: Review requested

#2651 Pin eventlet version
  AppTaskQueue/setup.py
Labels: Status: Demo requested

#2605 Simplify datastore error handling
  AppDB/appscale/datastore/datastore_distributed.py
  AppDB/appscale/datastore/scripts/datastore.py
Labels: Status: Demo requested

#2694 Adjustable max appservers
  AppController/djinn.rb
Labels: Status: Review requested

#2631 Add option to update all composite indexes
  AppDB/appscale/datastore/scripts/update_index.py
Labels: Status: Demo requested
