Repository AppScale/appscale, pull requests merged in 2018-04, with the labels that each got.

#2703 Upgrade to Cassandra 3.11.2
  AppDB/appscale/datastore/cassandra_env/templates/cassandra-env.sh
  AppDB/appscale/datastore/cassandra_env/templates/cassandra.yaml
  debian/appscale_install_functions.sh
Labels: Priority: High, Status: Review requested

#2634 Allow Java AppServer to use an external API Server
  AppServer_Java/build.xml
  AppServer_Java/src/com/google/appengine/tools/development/ApiProxyLocalFactory.java
  AppServer_Java/src/com/google/appengine/tools/development/ApiProxyLocalImpl.java
  AppServer_Java/src/com/google/appengine/tools/development/ApiServer.java
  AppServer_Java/src/com/google/appengine/tools/development/ApiServerFactory.java
  AppServer_Java/src/com/google/appengine/tools/development/ApiUtils.java
  AppServer_Java/src/com/google/appengine/tools/development/DevAppServerImpl.java
  AppServer_Java/src/com/google/appengine/tools/development/DevAppServerMain.java
  AppServer_Java/src/com/google/appengine/tools/development/SharedMain.java
Labels: Status: Review requested

#2655 Register instances with ZooKeeper
  AdminServer/appscale/admin/instance_manager/constants.py
  AppController/djinn.rb
  AppController/djinnServer.rb
  AppController/lib/app_controller_client.rb
  AppController/lib/hermes_client.rb
  AppController/test/tc_djinn.rb
  AppControllerClient/appscale/appcontroller_client/__init__.py
  AppManager/app_manager_server.py
  AppManager/test/unit/test_app_manager_server.py
  common/appscale/common/monit_interface.py
Labels: Status: Demo requested

#2674 Define the Cassandra cluster load balancing policy
  AppDB/appscale/datastore/cassandra_env/cassandra_interface.py
  AppDB/appscale/datastore/cassandra_env/constants.py
  AppDB/appscale/datastore/cassandra_env/get_token.py
  AppDB/appscale/datastore/cassandra_env/py_cassandra.py
  AppDB/appscale/datastore/cassandra_env/schema.py
  AppDB/appscale/datastore/scripts/upgrade_schema.py
Labels: Status: Approved for merge

#2706 Replace gen.Return() with bare return statements
  AdminServer/appscale/admin/__init__.py
  AppDB/appscale/datastore/cassandra_env/large_batch.py
  AppDB/appscale/datastore/scripts/datastore.py
  AppDB/appscale/datastore/scripts/transaction_groomer.py
  AppManager/app_manager_server.py
  AppTaskQueue/appscale/taskqueue/appscale_taskqueue.py
  common/appscale/common/async_retrying.py
  common/appscale/common/monit_interface.py
Labels: Status: Approved for merge

#2707 Do not reuse SourceManager future if it failed
  AdminServer/appscale/admin/instance_manager/source_manager.py
Labels: Status: Approved for merge

#2717 Upgrade to Cassandra 3.11.2
  AppDB/appscale/datastore/cassandra_env/templates/cassandra-env.sh
  AppDB/appscale/datastore/cassandra_env/templates/cassandra.yaml
  debian/appscale_install_functions.sh
Labels: Status: Approved for merge

#2716 Version bump to 3.5.1
  VERSION
Labels: Status: Approved for merge

#2710 Retry operations when nodes are not available
  AppDB/appscale/datastore/cassandra_env/retry_policies.py
Labels: Status: Approved for merge

#2702 Consider the version's previous ports as available
  AdminServer/appscale/admin/utils.py
Labels: Status: Build pending, Status: Demo requested

#2726 Fix dashboard app list
  AppDashboard/dashboard.py
  AppDashboard/templates/apps/delete.html
Labels: Status: Review requested

#2697 Give more informative messages for GQL errors
  AppDashboard/lib/datastore_viewer.py
Labels: Status: Demo requested

#2715 Clear cron jobs on a "down --clean"
  AppController/terminate.rb
Labels: Status: Demo requested

#2704 RM-542 Async datastore (communication with Cassandra)
  AppController/lib/datastore_server.rb
  AppController/lib/haproxy.rb
  AppDB/appscale/datastore/backup/datastore_backup.py
  AppDB/appscale/datastore/backup/datastore_restore.py
  AppDB/appscale/datastore/cassandra_env/cassandra_interface.py
  AppDB/appscale/datastore/cassandra_env/entity_id_allocator.py
  AppDB/appscale/datastore/cassandra_env/large_batch.py
  AppDB/appscale/datastore/cassandra_env/py_cassandra.py
  AppDB/appscale/datastore/cassandra_env/schema.py
  AppDB/appscale/datastore/cassandra_env/tornado_cassandra.py
  AppDB/appscale/datastore/datastore_distributed.py
  AppDB/appscale/datastore/entity_utils.py
  AppDB/appscale/datastore/groomer.py
  AppDB/appscale/datastore/scripts/data_layout.py
  AppDB/appscale/datastore/scripts/datastore.py
  AppDB/appscale/datastore/scripts/transaction_groomer.py
  AppDB/appscale/datastore/scripts/ua_server.py
  AppDB/appscale/datastore/scripts/update_index.py
  AppDB/appscale/datastore/scripts/view_records.py
  AppDB/appscale/datastore/utils.py
  AppDB/appscale/datastore/zkappscale/entity_lock.py
  AppDB/setup.py
  AppDB/test/functional/test_cassandra.py
  AppDB/test/functional/test_datastore.py
  AppDB/test/functional/test_datastore_v1.py
  AppDB/test/functional/test_soap_server.py
  AppDB/test/unit/test_backup.py
  AppDB/test/unit/test_backup_recovery_helper.py
  AppDB/test/unit/test_cassandra_backup.py
  AppDB/test/unit/test_cassandra_interface.py
  AppDB/test/unit/test_datastore_server.py
  AppDB/test/unit/test_entity_utils.py
  AppDB/test/unit/test_gcs_helper.py
  AppDB/test/unit/test_groomer.py
  AppDB/test/unit/test_restore.py
  AppDB/test/unit/test_zookeeper.py
  scripts/datastore_upgrade.py
  scripts/upgrade.py
Labels: Priority: High, Status: Review requested

#2698 Retry creating system users when AppScale starts
  AppController/djinn.rb
  AppController/lib/custom_exceptions.rb
  AppController/lib/user_app_client.rb
Labels: Status: Demo requested
