Repository AppScale/appscale, pull requests merged in 2018-08, with the labels that each got.

#2822 Autoscale logs
  AppController/djinn.rb
  AppController/lib/nginx.rb
Labels: Status: Demo requested

#2824 Reduce diffs with the 1.8.0 SDK (Part 2)
  AppDB/appscale/datastore/scripts/blobstore.py
  AppServer/LICENSE
  AppServer/dev_appserver.py
  AppServer/google/appengine/tools/adaptive_thread_pool.py
  AppServer/google/appengine/tools/appengine_rpc.py
  AppServer/google/appengine/tools/dev_appserver.py
  AppServer/google/appengine/tools/dev_appserver_login.py
  AppServer/google/appengine/tools/dev_appserver_main.py
  AppServer/google/appengine/tools/dev_appserver_upload.py
Labels: Status: Demo requested

#2700 Fix nginx config for handlers with secure field
  AppController/lib/helperfunctions.rb
  AppController/lib/nginx.rb
  AppDashboard/app.yaml
  AppDashboard/health_probe.py
Labels: Status: Review requested

#2777 Do not delete push task names immediately
  AppTaskQueue/appscale/taskqueue/distributed_tq.py
  AppTaskQueue/appscale/taskqueue/push_worker.py
  AppTaskQueue/appscale/taskqueue/task_name.py
Labels: Status: Build pending, Status: Demo requested

#2853 Use hmac helper for authentication check
  AdminServer/appscale/admin/base_handler.py
Labels: Status: Approved for merge

#2832 Add appscale-admin restart command
  APIServer/appscale/api_server/server.py
  AdminServer/appscale/admin/__init__.py
  AdminServer/appscale/admin/instance_manager/stop_instance.py
  AdminServer/appscale/admin/push_worker_manager.py
  AdminServer/appscale/admin/service_manager.py
  AdminServer/setup.py
  AppManager/app_manager_server.py
  common/appscale/common/constants.py
Labels: Status: Build pending, Status: Demo requested

#2835 Handle UpdateIndexes calls
  AdminServer/appscale/admin/__init__.py
  AdminServer/appscale/admin/appengine_api.py
  AdminServer/setup.py
Labels: Priority: High, Status: Demo requested

#2682 Error handling for starting or terminating instances
  AppController/djinn.rb
  AppController/lib/infrastructure_manager_client.rb
  AppController/test/tc_infrastructure_manager_client.rb
  InfrastructureManager/agents/base_agent.py
  InfrastructureManager/infrastructure_manager.py
  InfrastructureManager/infrastructure_manager_service.py
  InfrastructureManager/tests/test_ec2_agent.py
  InfrastructureManager/tests/test_ec2_agent_w_spot.py
  InfrastructureManager/tests/test_euca_agent.py
  InfrastructureManager/tests/test_gce_agent.py
  InfrastructureManager/tests/test_infrastructure_manager.py
  InfrastructureManager/tests/test_infrastructure_manager_service.py
Labels: Priority: High, Status: Demo requested

#2843 Add E2E test for queries involving ID separator
  AppDB/test/e2e/__init__.py
  AppDB/test/e2e/client.py
  AppDB/test/e2e/test_queries.py
  AppDB/test/e2e/test_transactions.py
Labels: Status: Review requested

#2847 Catch QueueNotFound error in TQ REST API
  AppTaskQueue/appscale/taskqueue/rest_api.py
Labels: Status: Approved for merge

#2826 Handle socket.error when doing HTTP requests from Hermes
  Hermes/appscale/hermes/stats/producers/cluster_stats.py
  Hermes/appscale/hermes/stats/producers/taskqueue_stats.py
  Hermes/appscale/hermes/stats/producers/tests/test_cluster_stats.py
  Hermes/appscale/hermes/stats/producers/tests/test_taskqueue.py
  Hermes/setup.py
Labels: Status: Demo requested

#2848 Do retries when creating table for pull queue in PG
  AppTaskQueue/appscale/taskqueue/queue.py
Labels: Priority: High
