Repository AppScale/appscale, pull requests merged in 2018-09, with the labels that each got.

#2862 Monit random csrf token and switch to appscale start/stop scripts
  AdminServer/appscale/admin/stop_services.py
  AppController/lib/monit_interface.rb
  AppController/terminate.rb
  AppManager/app_manager_server.py
  AppManager/test/unit/test_app_manager_server.py
  common/appscale/common/monit_interface.py
Labels: Status: Review requested

#2859 Bump version to 3.6.0
  VERSION
Labels: Priority: High

#2805 AppDashboard incorrect credential escaping
  AppDashboard/dashboard.py
  AppDashboard/templates/users/confirm.html
  AppDashboard/templates/users/login.html
  AppDashboard/templates/users/new.html
Labels: Status: Demo requested

#2866 Add hmac.compare_digest fallback
  AdminServer/appscale/admin/base_handler.py
  AdminServer/appscale/admin/utils.py
Labels: Status: Approved for merge

#2860 3.6.0 Release notes first draft
  RELEASE
  util/gen_release_notes.sh
Labels: Priority: High

#2834 Create additional table for tag queries
  AppTaskQueue/appscale/taskqueue/constants.py
  AppTaskQueue/appscale/taskqueue/distributed_tq.py
  AppTaskQueue/appscale/taskqueue/queue.py
Labels: Status: Review requested
