Repository AppScale/appscale, pull requests merged in 2018-05, with the labels that each got.

#2696 Use the ServiceManager to start datastore servers
  AdminServer/appscale/admin/__init__.py
  AdminServer/appscale/admin/service_manager.py
  AdminServer/appscale/admin/summary.py
  AdminServer/setup.py
  AdminServer/tests/test_service_manager.py
  AppController/djinn.rb
  AppController/lib/datastore_server.rb
  AppController/lib/haproxy.rb
  AppController/lib/hermes_client.rb
  AppController/lib/zkinterface.rb
  AppController/terminate.rb
  AppDB/appscale/datastore/dbinterface.py
  Hermes/appscale/hermes/stats/producers/process_stats.py
  InfrastructureManager/system_manager.py
  common/appscale/common/constants.py
  debian/control.jessie
  debian/control.trusty
  debian/control.wheezy
  debian/control.xenial
Labels: Priority: High, Status: Demo requested

#2742 Continue starting deployment if system user exists
  AppController/djinn.rb
  AppController/lib/custom_exceptions.rb
  AppController/lib/user_app_client.rb
Labels: Priority: High, Status: Review requested

#2656 Allow Go instances to use external API server
  AppServer/google/appengine/tools/devappserver2/module.py
  debian/appscale_install_functions.sh
Labels: Status: Build pending, Status: Demo requested

#2735 Treat commit operations on expired transactions as bad requests
  AppDB/appscale/datastore/datastore_distributed.py
Labels: Status: Demo requested

#2748 Handle "service" element
  AppServer/google/appengine/api/appinfo.py
  AppServer/google/appengine/api/appinfo_errors.py
  AppServer/google/appengine/tools/devappserver2/application_configuration.py
Labels: Status: Demo requested

#2756 AppController appserver check thread should exit when there is no work
  AppController/djinn.rb
Labels: Status: Review requested

#2657 Allow PHP instances to use external API server
  AppServer/google/appengine/tools/devappserver2/module.py
  AppServer/google/appengine/tools/devappserver2/php/runtime.py
  AppServer/google/appengine/tools/devappserver2/php/setup.php
  AppServer/php/sdk/google/appengine/runtime/RemoteApiProxy.php
Labels: Status: Approved for merge

#2720 Ensure Celery worker gets restarted
  AdminServer/appscale/admin/push_worker_manager.py
Labels: Status: Demo requested

#2712 Handle timeouts when querying available tasks
  AppTaskQueue/appscale/taskqueue/queue.py
Labels: Status: Demo requested

#2677 Don't silently ignore uncaught thread exceptions
  AppController/djinn.rb
  InfrastructureManager/system_manager.py
Labels: Status: Approved for merge

#2758 Make sure we create static entried for nginx
  AppController/lib/helperfunctions.rb
Labels: Status: Review requested

#2680 RM-550 Hermes taskqueue stats
  Hermes/appscale/hermes/stats/handlers.py
  Hermes/appscale/hermes/stats/producers/cluster_stats.py
  Hermes/appscale/hermes/stats/producers/proxy_stats.py
  Hermes/appscale/hermes/stats/producers/taskqueue_stats.py
  Hermes/appscale/hermes/stats/producers/tests/test-data/taskqueue-stats.json
  Hermes/appscale/hermes/stats/producers/tests/test_cluster_stats.py
  Hermes/appscale/hermes/stats/producers/tests/test_proxy.py
  Hermes/appscale/hermes/stats/producers/tests/test_taskqueue.py
  Hermes/appscale/hermes/stats/stats_app.py
  Hermes/setup.py
Labels: Status: Review requested

#2763 Fix list comprehension
  AppDB/appscale/datastore/datastore_distributed.py
Labels: Priority: High, Status: Approved for merge, Status: Review requested

#2768 Fix list comprehension
  AppDB/appscale/datastore/datastore_distributed.py
Labels: Priority: High, Status: Review requested

#2769 Version bump to 3.5.2
  VERSION
Labels: Priority: High, Status: Review requested

#2771 Release notes update for 3.5.2
  RELEASE
Labels: Priority: High, Status: Review requested

#2780 Increase open file limit for nginx
  debian/appscale_install_functions.sh
Labels: Status: Approved for merge
