Repository AppScale/appscale, pull requests merged in 2019-02, with the labels that each got.

#2922 Add standalone API Server from SDK
  AppServer/api_server.py
  AppServer/google/appengine/tools/boolean_action.py
  AppServer/google/appengine/tools/devappserver2/api_server.py
  AppServer/google/appengine/tools/devappserver2/api_server_test.py
  AppServer/google/appengine/tools/devappserver2/cli_parser.py
  AppServer/google/appengine/tools/devappserver2/constants.py
  AppServer/google/appengine/tools/devappserver2/devappserver2.py
  AppServer/google/appengine/tools/devappserver2/devappserver2_test.py
  AppServer/google/appengine/tools/devappserver2/dispatcher.py
  AppServer/google/appengine/tools/devappserver2/dispatcher_test.py
  AppServer/google/appengine/tools/devappserver2/module.py
  AppServer/google/appengine/tools/devappserver2/module_test.py
  AppServer/wrapper_util.py
Labels: Status: Approved for merge

#2916 IaaS restructure
  AppController/djinn.rb
  AppController/lib/infrastructure_manager_client.rb
  AppController/test/tc_infrastructure_manager_client.rb
  AppController/test/ts_all.rb
  AppDB/appscale/datastore/backup/cassandra_backup.py
  AppDB/appscale/datastore/backup/utils.py
  AppDB/test/unit/test_cassandra_backup.py
  InfrastructureManager/appscale/infrastructure/__init__.py
  InfrastructureManager/appscale/infrastructure/operation_ids_cache.py
  InfrastructureManager/appscale/infrastructure/system_manager.py
  InfrastructureManager/infrastructure_manager.py
  InfrastructureManager/infrastructure_manager_service.py
  InfrastructureManager/setup.py
  InfrastructureManager/tests/test_ec2_agent.py
  InfrastructureManager/tests/test_ec2_agent_w_spot.py
  InfrastructureManager/tests/test_euca_agent.py
  InfrastructureManager/tests/test_gce_agent.py
  InfrastructureManager/tests/test_infrastructure_manager.py
  InfrastructureManager/tests/test_infrastructure_manager_service.py
  InfrastructureManager/tests/test_system_manager.py
  InfrastructureManager/tests/test_utils.py
  InfrastructureManager/utils/__init__.py
  InfrastructureManager/utils/persistent_dictionary.py
  InfrastructureManager/utils/utils.py
  common/appscale/common/unpackaged.py
  debian/appscale_install.sh
  debian/appscale_install_functions.sh
Labels: Priority: High, Status: Demo requested

#2999 Add required ProjectGroomer argument
  AppDB/appscale/datastore/scripts/transaction_groomer.py
Labels: Priority: High
