Repository AppScale/appscale, pull requests merged in 2019-01, with the labels that each got.

#2949 Use gossip to find live Cassandra nodes
  AppController/djinn.rb
  AppController/lib/cassandra_helper.rb
Labels: Status: Build pending

#2944 Limit the number of entities fetched per statement
  AppDB/appscale/datastore/cassandra_env/cassandra_interface.py
Labels: Status: Approved for merge

#2958 Add support for the target field for cron jobs
  AdminServer/appscale/admin/__init__.py
  AdminServer/appscale/admin/utils.py
  AppController/djinn.rb
  AppController/lib/cron_helper.rb
Labels: Status: Approved for merge

#2871 Route instances as soon as they are registered
  AdminServer/appscale/admin/__init__.py
  AdminServer/appscale/admin/constants.py
  AdminServer/appscale/admin/instance_manager/instance_manager.py
  AdminServer/appscale/admin/instance_manager/routing_client.py
  AdminServer/appscale/admin/routing/__init__.py
  AdminServer/appscale/admin/routing/haproxy.py
  AdminServer/appscale/admin/routing/routing_manager.py
  AdminServer/appscale/admin/routing/templates/base.cfg
  AdminServer/appscale/admin/routing/templates/version.cfg
  AdminServer/setup.py
  AppController/djinn.rb
  AppController/lib/haproxy.rb
  common/appscale/common/constants.py
Labels: Status: Approved for merge

#2956 Improve speed of rebalance script
  AppDB/appscale/datastore/cassandra_env/rebalance.py
Labels: Priority: High, Status: Approved for merge

#2962 Use login property as ejabberd host
  AppController/djinn.rb
Labels: Status: Approved for merge

#2924 Ensure requests to channel path match
  AppController/lib/nginx.rb
Labels: Status: Approved for merge

#2961 Use login property when setting cron locations
  AppController/djinn.rb
Labels: Priority: High, Status: Demo requested

#2960 Drop requests that don't match the login property
  AppController/djinn.rb
  AppController/lib/nginx.rb
Labels: Priority: High, Status: Approved for merge

#2910 Bound update threads
  AppController/djinn.rb
Labels: Status: Demo requested

#2914 Ensure mutex
  AppController/djinn.rb
Labels: Status: Demo requested

#2974 Ensure newer version of PyYAML is installed
  AppTaskQueue/setup.py
  common/setup.py
Labels: Priority: High

#2983 Allow change instance
  AppController/djinn.rb
  AppController/lib/infrastructure_manager_client.rb
  AppController/test/tc_infrastructure_manager_client.rb
Labels: Status: Demo requested
